# -*- coding: utf-8 -*-
"""diwali sale EDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19U0DeFw94dQ5ym001Fg0pv3vcyAmL5h3
"""

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

data = files.upload()

ds = pd.read_csv("Diwali Sales Data (3).csv")
ds.head()

ds.info()

ds.isnull().sum()

# clearing null values & columns

ds.drop(['Status','unnamed1'], axis = 1, inplace = True)

ds.info()

ds.isnull().sum()

ds.shape

ds.dropna(inplace = True)

ds.isnull().sum()

#changing datatype of "Amount" from float to int

ds['Amount'] = ds['Amount'].astype('int')

ds['Amount'].dtypes

ds.info()

#rename columns

ds.rename(columns = {'Marital_Status':'Shaadi'}).head()

#use describe for selected columns

ds[['Amount', 'Age', 'Orders']].describe()

"""### ***Exploratory Data Analysis***

### ***With Gender***
"""

ds.columns

a = sns.countplot(x = 'Gender', data = ds)
for bars in a.containers:
  a.bar_label(bars)

sales = ds.groupby(['Gender'], as_index = False)['Amount'].sum().sort_values(by = 'Amount', ascending = False)

sns.barplot(x = 'Gender', y= 'Amount', data = sales)

"""### ***Age***"""

b = sns.countplot(data = ds, x = 'Age Group', hue = 'Gender')

for bars in b.containers:
  b.bar_label(bars)

sales_age = ds.groupby(['Age Group'], as_index= False)['Amount'].sum().sort_values(by = 'Amount', ascending = False)

sns.barplot(x = 'Age Group', y = 'Amount', data = sales_age)

"""### ***State***"""

#total number of orders by state

ds.columns

sales_state = ds.groupby(['State'], as_index = False)['Orders'].sum().sort_values(by = 'Orders', ascending = False)

sns.set(rc={'figure.figsize':(15,5)})
sns.barplot(data = sales_state, x = 'State', y = 'Orders')

#total amount from top 10 states

sales_state = ds.groupby(['State'], as_index = False)['Amount'].sum().sort_values(by = 'Amount', ascending = False)

sns.set(rc={'figure.figsize':(15,5)})
sns.barplot(data = sales_state, x = 'State', y = 'Amount')

"""### ***Marital Status***"""

c = sns.countplot(data = ds, x = 'Marital_Status')
sns.set(rc={'figure.figsize':(20,5)})

for bars in c.containers:
  c.bar_label(bars)

sales_state = ds.groupby(['Marital_Status', 'Gender'], as_index = False)['Amount'].sum().sort_values(by = 'Amount', ascending = False)

sns.set(rc={'figure.figsize':(10,5)})
sns.barplot(data = sales_state, x = 'Marital_Status', y = 'Amount', hue = 'Gender')

"""### ***Occupations***"""

sns.set(rc={'figure.figsize':(20,5)})
c = sns.countplot(data = ds, x = 'Occupation')

for bars in c.containers:
    c.bar_label(bars)

sales_state = ds.groupby(['Occupation'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False)

sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(data = sales_state, x = 'Occupation',y= 'Amount')

"""### ***Product category***"""

sns.set(rc={'figure.figsize':(20,5)})
d = sns.countplot(data = ds, x = 'Product_Category')

for bars in d.containers:
    d.bar_label(bars)

sales_state = ds.groupby(['Product_Category'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False).head(10)

sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(data = sales_state, x = 'Product_Category',y= 'Amount')

sales_state = ds.groupby(['Product_ID'], as_index=False)['Orders'].sum().sort_values(by='Orders', ascending=False).head(10)

sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(data = sales_state, x = 'Product_ID',y= 'Orders')

sales_state = ds.groupby(['Product_ID'], as_index=False)['Orders'].sum().sort_values(by='Orders', ascending=False).head(10)

sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(data = sales_state, x = 'Product_ID',y= 'Orders')