# -*- coding: utf-8 -*-
"""End to end analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CwJVrfaPc0auB1RwRUpUOYyf49P8vR_S
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

df = files.upload()

hotel = pd.read_csv("hotel_bookings 2.csv")

pd.DataFrame(hotel).head(5)

"""### ***Exploratory data analysis and data cleaning***"""

hotel.info()

hotel.shape

#we need to change object data type of this column as datetime data type.

hotel['reservation_status_date'] = pd.to_datetime(hotel['reservation_status_date'])

hotel.info()

hotel.describe(include = 'object')

for col in hotel.describe(include = 'object').columns:
  print(col)
  print(hotel[col].unique())
  print('-'*50)

hotel.isnull().sum()

hotel.drop(['company','agent'], axis = 1, inplace = True)
hotel.dropna(inplace = True)

hotel.isnull().sum()

hotel.describe()

hotel.isnull().sum()

hotel.describe()

"""### ***Data analysis and visualization***"""

cancelled_perc = hotel['is_canceled'].value_counts(normalize = True)
cancelled_perc

cancelled_perc = hotel['is_canceled'].value_counts(normalize = True)
print(cancelled_perc)

plt.figure(figsize = (5,4))
plt.title('Reservation status count')
plt.bar(['Not canceled', 'Canceled'], hotel['is_canceled'].value_counts(), edgecolor = 'k', width = 0.7)
plt.show()

plt.figure(figsize = (8,4))
axl = sns.countplot( x = 'hotel', hue = 'is_canceled', data = hotel, palette= 'Blues')
#legend_labels,_ = axl.get_legend_handles_labels()
#axl.legend(bbox_to_anchor(1,1))
plt.title('Reservation status in different hotels', size = 20)
plt.xlabel('hotel')
plt.ylabel('number of reservation')
plt.legend(['not_canceled','canceled'])
plt.show()

resort_hotel = hotel[hotel['hotel'] == 'Resort_hotel']
resort_hotel['is_canceled'].value_counts(normalize = True)

city_hotel = hotel[hotel['hotel'] == 'city_hotel']
city_hotel['is_canceled'].value_counts(normalize = True)

hotel = hotel[hotel['adr']<5000]

resort_hotel = resort_hotel.groupby('reservation_status_date')[['adr']].mean()
city_hotel = city_hotel.groupby('reservation_status_date')[['adr']].mean()

plt.figure(figsize = (15, 8))
plt.title('Average Daily Rate in city and Resort Hotel', fontsize = 30)
plt.plot(resort_hotel.index, resort_hotel['adr'], data = hotel, label = 'Resort hotel')
plt.plot(city_hotel.index, city_hotel['adr'], data = hotel, label = 'City hotel')
plt.legend(fontsize = 20)
plt.show()

hotel['month'] = hotel['reservation_status_date'].dt.month
plt.figure(figsize = (16,8))
ax1 = sns.countplot(x = 'month', hue = 'is_canceled', data = hotel)
plt.ylable = ('number of reservation')
plt.legend = (['not canceled', 'canceled'])
plt.show()